controller_list:
  - name: Alicia_controller
    type: $(arg fake_execution_type)
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint4
      - Joint5
      - Joint6
  - name: Gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - Gripper
initial:  # Define initial robot poses per group
  - group: Alicia
    pose: home
  - group: Gripper
    pose: open
