<?xml version="1.0"?>
<package format="2">
  <name>alicia_d_descriptions</name>
  <version>6.0.0</version>
  <description>Alicia-D robot description files</description>

  <maintainer email="synria@example.com">Synria Robotics</maintainer>
  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>

  <exec_depend>joint_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher_gui</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>rviz</exec_depend>
  <exec_depend>tf2_ros</exec_depend>

  <export>
  </export>
</package>
